# Site settings
title: artyfarty
email: mail@artyfarty.ru
description:  Домашняя страница artyfarty
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artyfarty.ru" # the base hostname & protocol for your site
twitter_username: molecula
github_username:  artyfarty

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
